app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/view/{id}', 'IndexController@view')->name('view');

Route::group(['prefix' => 'manager', 'as' => 'manager.'], function() {
    Route::resource('post', 'ManagerController');
});

Route::get('/{token}', 'UrlController@redirect');

app/app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $posts = Post::query()->paginate(5);

        return view('manager.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $categories = Category::query()->get();
        return view('manager.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PostRequest $request
     * @return RedirectResponse
     */
    public function store(PostRequest $request): RedirectResponse
    {
        Post::create($request->all());

        return redirect()->route('manager.post.index')
            ->with('success', 'Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return View
     */
    public function show(Post $post): View
    {
        return view('manager.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return View
     */
    public function edit(Post $post): View
    {
        $categories = Category::query()->get();
        return view('manager.edit', [
            'post'       => $post,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PostRequest $request
     * @param Post $post
     * @return RedirectResponse
     */
    public function update(PostRequest $request, Post $post): RedirectResponse
    {
        $post->update($request->validated());

        return redirect()->route('manager.post.index')
            ->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Post $post
     * @return RedirectResponse
     */
    public function destroy(Post $post): RedirectResponse
    {
        $post->delete();

        return redirect()->route('manager.post.index')
            ->with('success', 'Post deleted successfully');
    }
}

app/resources/views/manager/create.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{ route('manager.post.store') }}" method="POST">
        @csrf

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Category</label>
            <select aria-label="category" name="id_category" class="form-control custom-select">
                <option value="">Select category</option>
                @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Post header</label>
            <input name="name" type="text" class="form-control" id="exampleFormControlInput1" placeholder="post name">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Post text</label>
            <textarea name="text" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary mb-3">Save</button>
        </div>

    </form>

@endsection

app/resources/views/manager/edit.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{ route('manager.post.update',$post->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label for="postCategorySelector" class="form-label">Category</label>
            <select aria-label="category" name="id_category" class="form-control custom-select" id="postCategorySelector">
                <option value="">Select category</option>
                @foreach($categories as $category)
                    <option value="{{ $category->id }}" @if($category->id == $post->id_category) selected @endif>{{ $category->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="mb-3">
            <label for="postName" class="form-label">Post header</label>
            <input name="name" type="text" class="form-control" id="postName" placeholder="Post header" value="{{ $post->name }}">
        </div>

        <div class="mb-3">
            <label for="postText" class="form-label">Post text</label>
            <textarea name="text" class="form-control" id="postText" rows="3">{{ $post->text }}</textarea>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary mb-3">Save</button>
        </div>

    </form>

@endsection

app/resources/views/manager/index.blade.php
@extends('layouts.app')

@section('content')

    <a class="btn btn-primary mb-3" href="{{ route('manager.post.create') }}">Create New Post</a>

    @foreach ($posts as $post)

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ $post->name }}
                    <span class="badge bg-secondary">
                        {{ $post->category->name }}
                    </span>
                </h5>
                <p class="card-text">{{ $post->text }}</p>

                <form action="{{ route('manager.post.destroy',$post->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('manager.post.show',$post->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('manager.post.edit',$post->id) }}">Edit</a>

                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>

    @endforeach

    {{$posts->links('vendor.pagination.bootstrap-4')}}

@endsection

app/resources/views/manager/show.blade.php
@extends('layouts.app')

@section('content')
    <p>This is user {{ $post->id }}</p>
@endsection